---
# Containers are under development
containers:
  - name: gitea
    image: gitea/gitea:1.16.8-rootless
    ports:
      - name: gitea
        containerPort: 3000
        protocol: TCP
    environment:
      GITEA__DEFAULT__RUN_MODE: dev
      GITEA__database__DB_TYPE: sqlite3
      GITEA__database__PATH: /data/gitea/gitea.db
      GITEA__picture__DISABLE_GRAVATAR: "true"
      GITEA__repository__DEFAULT_PRIVATE: "false"
      GITEA__repository__DEFAULT_PUSH_CREATE_PRIVATE: "false"
      GITEA__repository__ENABLE_PUSH_CREATE_ORG: "true"
      GITEA__repository__ENABLE_PUSH_CREATE_USER: "true"
      GITEA__repository__ONLY_ALLOW_PUSH_IF_GITEA_ENVIRONMENT_SET: "false"
      GITEA__security__INSTALL_LOCK: "true"
      GITEA__server__SSH_DOMAIN: http://gitea
      GITEA__service__DISABLE_REGISTRATION: "true"
      GITEA__service__REQUIRE_SIGNIN_VIEW: "false"
      GITEA__webhook__ALLOWED_HOST_LIST: '*'
    volumeMounts:
      - name: gitea-varlib
        mountPath: /var/lib/gitea/
      - name: gitea-data
        mountPath: /data/
      - name: gitea-etc
        mountPath: /etc/gitea
    volumes:
      - name: gitea-data
        emptyDir: {}
      - name: gitea-etc
        emptyDir: {}
      - name: gitea-varlib
        emptyDir: {}
    commands:
      - >
        gitea admin user create --admin --username gitea --password gitea
        --email dummy@dummy.com --must-change-password=false
      - >
        curl -X POST -H "accept: application/json"
        -H "Content-Type: application/json"
        -u 'gitea:gitea'
        -d '{"username": "student", "full_name": "student",
        "description": "student"}'
        http://localhost:3000/api/v1/orgs
      - >
        curl -X POST -H "accept: application/json"
        -H "Content-Type: application/json"
        -u 'gitea:gitea'
        -d '{"clone_addr":
        "https://github.com/ansible/ansible-lightspeed-demos",
        "repo_name": "acme_corp", "owner": "student",
        "uid": 2, "private": false}'
        http://localhost:3000/api/v1/repos/migrate
      - >
        curl -X PATCH -H "accept: application/json"
        -H "Content-Type: application/json"
        -u 'gitea:gitea'
        -d '{"default_branch": "devel"}'
        http://localhost:3000/api/v1/repos/student/acme_corp
    memory: 2Gi
    services:
      - name: gitea
        ports:
          - port: 3000
            protocol: TCP
            targetPort: 3000
            name: gitea
    routes:
      - name: gitea
        host: gitea
        service: gitea
        targetPort: 3000
        tls: true
        tls_termination: Edge

virtualmachines:
  - name: "control"
    image: "base-zero-aap-2.5-container-ce"
    memory: "16G"
    cores: 4
    image_size: "30Gi"
   # disk_type: "scsi"
   # bootloader: "efi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
      - secondary
    userdata: |-
      #cloud-config
      user: rhel
      password: {{ common_password }}
      chpasswd: { expire: False }
      runcmd:
        - sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config
        - systemctl reload sshd
    services:
      - name: control-https
        ports:
          - port: 443
            protocol: TCP
            targetPort: 443
            name: control-https
      - name: cockpit
        ports:
          - port: 9090
            protocol: TCP
            targetPort: 9090
            name: cockpit
    routes:
      - name: control-https
        host: control
        service: control-https
        targetPort: 443
        tls: true
        tls_termination: reencrypt
        tls_destinationCACertificate: |
          -----BEGIN CERTIFICATE-----
          MIIF1jCCA76gAwIBAgIUBQZlbUZlOmMKhspO9U4/nTJAXAEwDQYJKoZIhvcNAQEL
          BQAwgYIxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4G
          A1UEBwwHUmFsZWlnaDEQMA4GA1UECgwHUmVkIEhhdDEQMA4GA1UECwwHQW5zaWJs
          ZTEkMCIGA1UEAwwbQW5zaWJsZSBBdXRvbWF0aW9uIFBsYXRmb3JtMB4XDTI1MDQy
          MzA4MjEyOVoXDTM1MDQyMTA4MjEyOVowgYIxCzAJBgNVBAYTAlVTMRcwFQYDVQQI
          DA5Ob3J0aCBDYXJvbGluYTEQMA4GA1UEBwwHUmFsZWlnaDEQMA4GA1UECgwHUmVk
          IEhhdDEQMA4GA1UECwwHQW5zaWJsZTEkMCIGA1UEAwwbQW5zaWJsZSBBdXRvbWF0
          aW9uIFBsYXRmb3JtMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA2Ytu
          a9MM9qr0UBvlIJPXmeSjzQXmx+CJwQAhDoR8MgOkjvWjjEdsX4VHBfQTO58d5sPr
          oNg95GRe9y9Gjt6Lh7szLk70Q766Ncq8OIBYieiVKctIV+ZZmX7+bBcyzbII/0C9
          Ili3lNd+XKfl5vmCWoYyuQncC1FZgVpHqZDP/+RCCMThdKEvugbQUmXF6pmEFF7Z
          8PxYpxnVDX2ipOfWcjZDm6pTBd5+dzXHQVsWe25kY6QW0zEYzPJb3q0gP7oNz1uV
          rXgYBnKQ8NdoSGtS7w9bvSw28Bf1ZFTvBKeCxWNeoJbiszqdsDd6PEwb4uE1Tr6D
          qsLfPgvQzngQ+a7YrZ+M6GskQkfk+ZWMK8h6066p27Tzs6/9jMiCFuKwRuKWy9Qi
          DdCSnwVIw4VB40ysoAHprxBHq4y/YJ2RDiC9EehTXsQf/uAy3M7KBBjVGlMfXxUE
          NfjbeMdSQip04jKQGhJf8teXTymfcjlGaoCtymB+h4s3hc1T7DjfR0Q1Gd3AIL/p
          lHOgU4TMBzeghqeDRbY4YQRSI1aF/hzTvAJzMaONs161buKOQ47O5UGGJYHHlJbf
          aI0s3Mhld1YvIFk78A4tFI9GIwzj4IzVmCv4MZHg2BXKAU6m3Y6bYNabqP6Ho4Fs
          DZOVkMvwTGKGfRxjdp0kx6HxNmjnVDMXGM9g8cECAwEAAaNCMEAwDgYDVR0PAQH/
          BAQDAgIEMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFFugxH0taHxJ0/d71phl
          a1Vt78fTMA0GCSqGSIb3DQEBCwUAA4ICAQApZCo7gI0xdk2TxjOcq+BdNsOvKjWL
          ADceDM78oPy0xpgKd2u9INITzIY2f4KGcepXslnlMQQvny80N1LXu9Tkn4rhoU03
          DXb9bXSr44T3fIf4JFU2iv5Hb6Az/DiQ3o9fZnhpW0AmzR1LmZUuFBJZefFBMMKl
          s2W9C3f3nUPzi1qrGSXszXXbIDYsRMhax/MxWR9mxITuN3T6PhW8A1LyQ8dWRCLw
          jFFcNuGjlR8w16XhRCw8uA1RzVwNWoUGvMiapboR25N0DLVCG8qf/mdEI4re8MhM
          EYHugB/e7vRx6iV9ov7jJSB8BrBPWy/7ncebWIf8OvjM2UcUk0hciAQGD4Udbb3s
          LGcpjZRJDrnpBdp+CJMCNNjoI0wLbmRDEVPGOSkJSmnj+8VTlQ5s+Dxvj2hh/rq7
          APwxbIl1YBpTx65KwhacJbXSByk8bnwEQdRo240kC5ggC6twb/vvslRortZtyfqw
          E/xGAKc9LOIFiqk1f0IU2ssEBvSFvYjypXsGnFITamNN2lMS2k5XQIA4avwWsoO4
          rRLV87ua9S7g31PTYCMJBGw/B3PXhXjJG/eXgLyhEoUQP/fqeGiPEBzagyo71qL5
          fH5qke1XR5LFGpndX1GuSVBhdZq94x0aGXWTQCDNIPQ3QtrQ64PBF1vRFdJ6o/FI
          uEOWpQhGYHMC0A==
          -----END CERTIFICATE-----
      - name: cockpit
        host: cockpit
        service: cockpit
        targetPort: 9090
        tls: true
        tls_termination: Edge
  - name: "vscode"
    image: "devtools-ansible"
    memory: "16G"
    cores: 4
    image_size: "20Gi"
    disk_type: "scsi"
    bootloader: "efi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
      - secondary
    services:
      # - name: vscode-http
      #   ports:
      #     - port: 80
      #       protocol: TCP
      #       targetPort: 80
      #       name: vscode
      - name: vscode-8080
        ports:
          - port: 8080
            protocol: TCP
            targetPort: 8080
            name: vscode
      - name: pgadmin
        ports:
          - port: 8083
            protocol: TCP
            targetPort: 8083
            name: pgadmin
    routes:
      # - name: vscode-http
      #   host: vscode
      #   service: vscode-http
      #   targetPort: 80
      #   tls: true
      #   tls_termination: Edge
      - name: vscode-8080
        host: vscode
        service: vscode-8080
        targetPort: 8080
        tls: true
        tls_termination: Edge
      - name: pgadmin
        host: pgadmin
        service: pgadmin
        targetPort: 8083
        tls: true
        tls_termination: Edge
    userdata: |-
      #cloud-config
      user: rhel
      password: {{ common_password }}
      chpasswd: { expire: False }
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd
